name: Build and Release RustDesk Desktop Clients

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, ubuntu-22.04, macos-12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Configure Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev

      - name: Set RustDesk environment variables
        run: |
          echo "RUSTDESK_RENDEZVOUS_SERVER=${{ secrets.RUSTDESK_RENDEZVOUS_SERVER }}" >> $GITHUB_ENV
          echo "RUSTDESK_PUBLIC_KEY=${{ secrets.RUSTDESK_PUBLIC_KEY }}" >> $GITHUB_ENV

      - name: Build RustDesk
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-rustdesk-client
          path: |
            target/release/rustdesk.exe
            target/release/rustdesk
            target/release/rustdesk.app

  create-release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_name == 'master'
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4

      - name: Get artifact paths
        id: get_paths
        run: |
          echo "windows_path=windows-2022-rustdesk-client/rustdesk.exe" >> $GITHUB_OUTPUT
          echo "ubuntu_path=ubuntu-22.04-rustdesk-client/rustdesk" >> $GITHUB_OUTPUT
          echo "macos_path=macos-12-rustdesk-client/rustdesk.app" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.get_paths.outputs.windows_path }}
            ${{ steps.get_paths.outputs.ubuntu_path }}
            ${{ steps.get_paths.outputs.macos_path }}
          name: RustDesk ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
