name: Flutter Nightly Build

on:
  # schedule:
  #   # schedule build every night
  #   - cron: "0 0 * * *"
  workflow_dispatch:

# --- Añade esta sección aquí ---
  permissions:
    contents: write # Esto otorga permisos de escritura al GITHUB_TOKEN para todo el workflow
  # -----------------------------

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly"
